/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report whether the server is fit to answer queries
         * @description Unauthenticated on purpose: a health check that needs a credential is
         *     one more thing that can fail for a reason unrelated to health.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the current metrics
         * @description The Prometheus text exposition format: queries by transport, type and
         *     response code, latency, response sizes, drops, truncations, what the
         *     snapshot being answered from holds, and the Go runtime and process
         *     collectors that come with any Go exporter.
         *
         *     Authenticated like everything else here. What a server is asked, how
         *     often and by how many zones is operational detail, and a scraper can
         *     carry a bearer token: Prometheus has had `authorization` in its scrape
         *     configuration for years. `/healthz` is the one endpoint that needs no
         *     credential, because a load balancer cannot be given one.
         *
         *     The response carries the exposition format's version in its
         *     `Content-Type`, which is where a scraper reads it.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Watch queries as they are answered
         * @description A live tail of the exchanges matching the filter, as Server-Sent
         *     Events. Two kinds of message arrive:
         *
         *     - `query`, one per exchange, carrying a `QueryEvent`.
         *     - `status`, whenever what the stream is leaving out changes and every
         *       few seconds regardless, carrying a `StreamStatus`. It says what the
         *       stream is sampling at and how much it has dropped, because a stream
         *       that quietly leaves things out while looking complete is worse than
         *       one that admits to showing every fiftieth query
         *       (docs/decisions/ D9).
         *
         *     The filter is applied before anything is buffered, so watching one zone
         *     stays complete however busy the rest of the server is. A watcher that
         *     stops reading loses its oldest exchanges, never its newest: this is a
         *     live view, and it is never allowed to slow a query down.
         *
         *     How many watchers may be open at once is bounded, because each one
         *     costs the query path a filter evaluation per query. A request past the
         *     bound is refused with 503.
         */
        get: operations["streamQueries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List zones */
        get: operations["listZones"];
        put?: never;
        /** Create a zone */
        post: operations["createZone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zones/{zoneId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        /**
         * Read one zone
         * @description Everything a listing carries, and the one diagnosis a zone can carry
         *     that nothing about it looks wrong for. It is computed here rather than
         *     left to `/check` because somebody who has to know to run a check in
         *     order to be told their delegation is broken has been told nothing. It
         *     costs the zone's NS records and one lookup per name server, not a walk
         *     of the zone, which is what makes that affordable.
         */
        get: operations["getZone"];
        put?: never;
        post?: never;
        /** Delete a zone and everything in it */
        delete: operations["deleteZone"];
        options?: never;
        head?: never;
        /**
         * Change a zone's own settings
         * @description Only the fields that are present are changed. The zone's records are
         *     not touched, and the zone cannot be renamed: every owner name, every
         *     sort key and the whole journal belong to the name it has.
         *
         *     Changing anything that is served advances the serial, like any other
         *     change. Changing nothing writes nothing.
         */
        patch: operations["updateZone"];
        trace?: never;
    };
    "/zones/{zoneId}/records": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        /** List the records of a zone */
        get: operations["listRecords"];
        put?: never;
        /**
         * Add a record to a zone
         * @description An address record may generate a PTR in the reverse zone answering for
         *     it. What that produced, and what it could not produce, comes back in
         *     the response rather than in a log line (docs/decisions/ D3 and D6).
         */
        post: operations["createRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zones/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bring a whole zone in from a zonefile
         * @description The body is the file itself, in the presentation format of RFC 1035 §5.
         *     The zone it describes is wherever its SOA sits, so the name is not sent
         *     separately and cannot be sent inconsistently.
         *
         *     The serial in the file is the serial the zone starts at. A migrated
         *     zone that restarted at 1 would look older than itself to every
         *     secondary that has already seen it (RFC 1982 §3.2), which is the single
         *     most common way to break a migration (docs/decisions/ D2).
         *
         *     `$INCLUDE` is refused: a file arriving here that could pull in a path
         *     would read this server's filesystem out loud.
         *
         *     Records that a delegation in the same file makes unanswerable are left
         *     out rather than failing the whole file, and come back in `skipped`.
         *     Real zones carry them, and a migration that stops on one is a migration
         *     nobody finishes.
         *
         *     The zone must not already exist. A file is the complete contents of a
         *     zone, so bringing one into a zone that holds records is a replacement
         *     rather than an import.
         */
        post: operations["importZone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zones/{zoneId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        /**
         * Write a zone out as a zonefile
         * @description The presentation format of RFC 1035 §5, which any other authoritative
         *     server reads. Every name is absolute and every record carries its own
         *     TTL and class, so no line means something different when it is copied
         *     out; records come out in the canonical order of RFC 4034 §6.1, so
         *     exporting the same zone twice is the same bytes and a diff of two
         *     exports is a diff of two zones.
         *
         *     A disabled record is left out. It is not part of the zone as it
         *     answers, and a file has nowhere to say "present but switched off".
         */
        get: operations["exportZone"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zones/{zoneId}/check": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        /**
         * Report what is wrong with a zone as it stands
         * @description Every rule the write path enforces, applied to the zone as it is
         *     stored.
         *
         *     A write is checked against the names it touches, and against the names
         *     a new delegation would put out of reach, so a zone edited only through
         *     this API stays sound. What this finds is what did not arrive that way:
         *     data written before a rule existed, or a hand on the database file.
         *
         *     It reports rather than refuses. A name with more than one problem
         *     yields the first of them, and the list stops at a thousand findings:
         *     a zone past that has one systematic fault rather than a thousand
         *     separate ones.
         *
         *     Nothing is written. Repairing what this names is ordinary editing.
         */
        get: operations["checkZone"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zones/{zoneId}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write the reverse entries this zone's records imply and does not have
         * @description Reverse automation reacts to changes, so a zone that arrives after the
         *     records it should hold has nothing to react to. A reverse zone created
         *     for a network already in use starts empty, however many addresses are
         *     already named in it, and this is what fills it: one commit for
         *     everything missing.
         *
         *     It only adds. An entry that became obsolete was taken away by the
         *     change that obsoleted it, and one somebody detached is theirs to keep,
         *     so nothing here removes anything.
         *
         *     A zone that needs nothing is left alone and answers with no commit.
         */
        post: operations["reconcileZone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zones/{zoneId}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a zone to the state it had at a serial
         * @description The difference between the zone as it stands and the zone as it stood
         *     is written as a **new** commit that moves forward to that state. It is
         *     not a rewind: a secondary that has already seen serial 90 will never
         *     accept a jump back to 42, because RFC 1982 arithmetic makes 42 older
         *     and RFC 1995 has no way to express going backwards.
         *
         *     Records that did not change in between are not touched, so they keep
         *     their identity, their comments and the history pointing at them.
         *     Records the server generated are not restored directly: they follow
         *     from the records they were generated from, so restoring those is what
         *     moves them.
         *
         *     A rollback to the serial the zone is already at changes nothing and
         *     answers with no commit.
         */
        post: operations["rollbackZone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zones/{zoneId}/rrsets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Make the named RRsets exactly what is given
         * @description An RRset (everything sharing an owner name, class and type) is the
         *     unit DNS answers with (RFC 2181 §5), and therefore the unit a record
         *     editor edits. Sending the set rather than a list of additions and
         *     removals means the client says what it wants to be true, and the server
         *     works out the difference; a record whose data did not change keeps its
         *     identity, and with it its comment, its provenance and the history
         *     pointing at it.
         *
         *     Only the RRsets named here are touched. An empty `records` removes one.
         *
         *     Everything in one request becomes one commit, so a page of edits saved
         *     together is one line in the history and one point to roll back to.
         *
         *     The RRsets are named in the body rather than in the path because a DNS
         *     label may hold any octet, `/` among them, so there is no path form that
         *     is safe for every name.
         */
        put: operations["replaceRRsets"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{recordId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a record. */
                recordId: components["parameters"]["RecordID"];
            };
            cookie?: never;
        };
        /** Read one record */
        get: operations["getRecord"];
        put?: never;
        post?: never;
        /** Delete a record */
        delete: operations["deleteRecord"];
        options?: never;
        head?: never;
        /**
         * Change a record
         * @description Only the fields that are present are changed. The record keeps its
         *     identity, and with it its comment, its provenance and the history
         *     pointing at it, which is what tells an edit apart from a delete and an
         *     add.
         *
         *     A record the server generated is refused, naming the record it came
         *     from; detach it first to take it over (docs/decisions/ D4).
         */
        patch: operations["updateRecord"];
        trace?: never;
    };
    "/records/{recordId}/detach": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a record. */
                recordId: components["parameters"]["RecordID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take over a generated record
         * @description The record keeps its data and its identity, loses its link to the
         *     record it was generated from, and the automation stops maintaining it
         *     (docs/decisions/ D4). A record that was already authored is returned
         *     unchanged: asking for it to be nobody's derivative has got what it
         *     asked for.
         */
        post: operations["detachRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{recordId}/canonical": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a record. */
                recordId: components["parameters"]["RecordID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make this the name an address reverses to
         * @description Several names on one address is ordinary, and only one of them can be
         *     the answer to a reverse lookup. Where the address record named here is
         *     not that one, this hands it the entry and takes it from whatever
         *     generated one holds it.
         *
         *     The record itself does not change. What changes is the reverse zone,
         *     in a commit of its own like any other change the automation makes.
         *
         *     An entry somebody wrote by hand is left alone: detaching a generated
         *     record is how a person says to stop maintaining it, and taking it back
         *     would make detaching mean nothing (docs/decisions/ D4). A record that
         *     already holds the entry is answered without anything being written.
         */
        post: operations["makeRecordCanonical"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report who this request is authenticated as
         * @description What an interface asks when it loads, to find out whether it has to
         *     show a login at all, and what to grey out if it does not.
         */
        get: operations["getSession"];
        put?: never;
        /**
         * Exchange a token for a browser session
         * @description The web interface does not hold a long-lived token. It posts one here
         *     once and receives an `httpOnly` session cookie, which no script that
         *     gets injected into the page can read, which is the whole point.
         *
         *     A second, readable cookie carries a CSRF value. Every state-changing
         *     request authenticated by the session cookie has to repeat it in the
         *     `X-Wegweiser-CSRF` header. `SameSite=Strict` already blocks a
         *     cross-site form post; this is the second layer. A request that
         *     authenticates with a bearer token skips the check, because CSRF needs
         *     ambient credentials and a bearer token is not ambient.
         *
         *     Unauthenticated, because a request that could authenticate would not
         *     need this. The token inside is checked the same way and is rate-limited
         *     the same way.
         */
        post: operations["createSession"];
        /**
         * End the session
         * @description The cookies are cleared and the session is forgotten here, so a copy of
         *     the cookie taken beforehand stops working too. The token it was opened
         *     with is untouched.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the server-wide settings
         * @description These are the defaults a zone that says nothing about itself inherits.
         *     They live in the database, so changing one takes effect on the next
         *     write without a restart (docs/decisions/ D11).
         */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the server-wide settings
         * @description A field that is absent is left alone, so a client may send only what it
         *     means to change.
         */
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the tokens that may use this API
         * @description Revoked and expired tokens are listed too, so that a name in the
         *     history can still be looked up. No response ever carries a secret: what
         *     is stored is its SHA-256, and the leading characters kept in the clear
         *     are there to tell two tokens apart, not to authenticate with.
         */
        get: operations["listTokens"];
        put?: never;
        /**
         * Mint a token
         * @description The secret comes back in this response and never again. It is 256 bits
         *     from a cryptographic source; what the server keeps is its SHA-256, so a
         *     copy of the database is not a copy of the credentials.
         */
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a token. */
                tokenId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Withdraw a token
         * @description The token is marked unusable rather than removed, so that the history
         *     it appears in still names something. Revoking a token that is already
         *     revoked changes nothing and is not an error.
         *
         *     The last token that can still administer the server is refused: a
         *     server nobody can reach is not a state this API will put itself in.
         */
        delete: operations["revokeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tsig-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the keys a secondary may sign a transfer with
         * @description Revoked keys are listed too, so that a name a secondary still has
         *     configured can be looked up. No listing carries a secret; reading one
         *     back is a request of its own.
         */
        get: operations["listTSIGKeys"];
        put?: never;
        /**
         * Create a key
         * @description The secret comes back in this response. Unlike an API token it can be
         *     read again, because verifying a signature means recomputing the MAC and
         *     this server therefore has to keep it.
         *
         *     Leave the secret out and one is generated, at least as long as the hash
         *     output of the algorithm (RFC 8945 section 8). Send one to match a
         *     secondary that already has a key, base64 as every other implementation
         *     writes it.
         */
        post: operations["createTSIGKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tsig-keys/{keyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a key. */
                keyId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Withdraw a key
         * @description The key stops signing and its secret is cleared, which is the one thing
         *     revoking a token does not do: a token leaves only a hash behind, and a
         *     key would leave material nothing will read again. The row stays so the
         *     name and the dates still read, and the name is then free for a
         *     replacement.
         *
         *     Revoking a key that is already revoked changes nothing and is not an
         *     error.
         */
        delete: operations["revokeTSIGKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tsig-keys/{keyId}/secret": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a key. */
                keyId: string;
            };
            cookie?: never;
        };
        /**
         * Read a key's secret
         * @description Separate from the listing so that a secret is shown when somebody asked
         *     for it and not when they were looking at something else. It is not a
         *     boundary: the database holds the secret either way.
         *
         *     A revoked key has none, and this is then a refusal rather than an empty
         *     answer.
         */
        get: operations["readTSIGKeySecret"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/secondary-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Write the configuration a secondary needs
         * @description The zones this server holds, rendered as a configuration file for the
         *     software running at the other end. It carries the transfer key's secret
         *     in clear, which is what it is for, so it needs the `admin` scope for the
         *     same reason reading that secret does.
         *
         *     The output is deterministic. Regenerating it produces the same bytes
         *     when nothing has changed, so it can live under configuration management
         *     without a diff on every run.
         *
         *     What is reported beside it is the arrangement rather than the syntax: a
         *     transfer list nobody is on, a key that grants nothing, a secondary the
         *     notifications do not reach. Each of those renders a file that is
         *     perfectly formed and does not work.
         */
        get: operations["getSecondaryConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/secondary-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Say what each secondary holds
         * @description One entry per zone per secondary on the notify list, saying what that
         *     secondary last said its serial was and how that compares with what this
         *     server publishes now.
         *
         *     A secondary is asked once a notification to it has been answered or
         *     given up on, and at least hourly whether anything changed or not. Until
         *     the first question about a pair has finished it is reported as unasked,
         *     which is a state of its own: reporting it as in step would be the one
         *     thing this is here to stop.
         *
         *     Nothing is reported while a notification is outstanding. A secondary
         *     that has just been told and has not fetched yet is in flight rather than
         *     behind, and a report that cannot tell those apart is one nobody reads.
         */
        get: operations["getSecondaryStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List commits, newest first
         * @description Every write is a commit, so this is the whole history of the server.
         *     Commits are listed without their events, which is what makes a page of
         *     history cheap on a zone that has been edited for years; read one commit
         *     to get the changes it made.
         *
         *     A commit outlives the zone it describes, so the history of a deleted
         *     zone is still here, under the name it had.
         */
        get: operations["listCommits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commits/{commitId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a commit. */
                commitId: string;
            };
            cookie?: never;
        };
        /**
         * Read one commit and everything it changed
         * @description The events are the diff: every record that was removed and every record
         *     that was added, both carrying their full data. That is what RFC 1995 §2
         *     asks of an incremental transfer, and it is also what an interface needs
         *     to render the change and what restoring an earlier state needs to undo
         *     it.
         */
        get: operations["getCommit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A failure, in the shape of RFC 9457. Anything a client has to act on
         *     travels as a field rather than as prose in `detail`, because no client
         *     should be parsing English.
         */
        Problem: {
            /** @description A URI reference naming the kind of failure. */
            type: string;
            /** @description A short, stable summary of the kind of failure. */
            title: string;
            /** @description The HTTP status code, repeated for clients that lost it. */
            status: number;
            /** @description What went wrong with this particular request. */
            detail?: string;
            /** @description The request this failure belongs to. */
            instance?: string;
            /** @description Reverse entries that were not written because another name already claims the address. */
            conflicts?: components["schemas"]["Conflict"][];
            /** @description Reverse zones that would be needed and do not exist. */
            missingZones?: components["schemas"]["MissingZone"][];
        };
        /**
         * @description What happens when an address already answers a reverse lookup with some
         *     other name (docs/decisions/ D3).
         *
         *     - `first-wins` keeps the entry that is there and reports the conflict.
         *       The default, and the only value that never changes an answer nobody
         *       asked to change.
         *     - `last-wins` replaces a generated entry with the new one, still
         *       reporting the conflict. An entry somebody wrote by hand is never
         *       replaced.
         *     - `multi` keeps both, which is the literal reading of "generate the
         *       reverse entry" and turns a routine change into a multi-record PTR set
         *       that reverse-lookup checks are not built for.
         *     - `reject` refuses the whole change.
         * @enum {string}
         */
        ReverseConflictPolicy: "first-wins" | "last-wins" | "multi" | "reject";
        Settings: {
            reverseConflictPolicy: components["schemas"]["ReverseConflictPolicy"];
            transferAllow: components["schemas"]["TransferAllow"];
            notifyTargets: components["schemas"]["NotifyTargets"];
        };
        /** @description A field that is absent is left as it is. */
        UpdateSettings: {
            reverseConflictPolicy?: components["schemas"]["ReverseConflictPolicy"];
            transferAllow?: components["schemas"]["TransferAllow"];
            notifyTargets?: components["schemas"]["NotifyTargets"];
        };
        /**
         * @description Who is told when a zone changes, as addresses with an optional port.
         *     An empty list tells nobody, and then a secondary finds out when its
         *     own refresh timer fires. This is a separate list from transferAllow:
         *     that one decides who may take a copy, this one names where a
         *     notification can arrive, so it holds addresses rather than prefixes.
         *
         *     A `key:<name>` after the address signs the notification with that TSIG
         *     key, for a secondary that insists on one.
         */
        NotifyTargets: string[];
        /**
         * @description Who may transfer a zone off this server, whole or as what has changed
         *     since their copy, as addresses or CIDR prefixes. An empty list is
         *     nobody, which is where a server starts: a zone is an inventory of a
         *     network, and a copy handed out cannot be taken back. A bare address is
         *     stored as the single-host prefix it means.
         */
        TransferAllow: string[];
        Health: {
            /** @enum {string} */
            status: "serving" | "starting";
            version: string;
            /** @description Zones the query path currently answers for. */
            zones: number;
            /** @description Records the query path currently answers from. */
            records: number;
        };
        /** @description One exchange, as a watcher sees it. */
        QueryEvent: {
            /**
             * Format: date-time
             * @description When the query was read.
             */
            at: string;
            /**
             * @description How long the exchange took, in microseconds, from reading the
             *     query to having written the response.
             */
            latencyUs: number;
            /** @description The address the query came from. */
            client: string;
            /** @description The port it came from. */
            port?: number;
            /** @enum {string} */
            transport: "udp" | "tcp";
            /**
             * @description The question name, in the casing the client sent it, not the
             *     casing this server stores, which is always lowercase.
             */
            name: string;
            type: string;
            class: string;
            /** @description The response code sent, by mnemonic. Meaningless when `dropped` is set. */
            rcode: string;
            /** @description The response, in octets on the wire. Zero when nothing was sent. */
            size: number;
            /** @description Whether the response was cut to fit the transport and marked TC (RFC 1035 §4.1.1). */
            truncated: boolean;
            /**
             * @description Whether nothing was sent at all. Two messages have no safe reply,
             *     and a query that got silence is exactly what somebody debugging is
             *     looking for.
             */
            dropped: boolean;
        };
        /**
         * @description What this stream is leaving out. Part of the interface rather than a
         *     debug detail: a stream that is sampling has to say so, or what it shows
         *     reads as everything that happened.
         */
        StreamStatus: {
            /** @description Exchanges that passed the filter. */
            matched: number;
            /** @description How many of those reached this watcher. */
            sent: number;
            /** @description How many were left out because the filtered stream was faster than the cap. */
            sampled: number;
            /** @description How many were thrown away because this watcher was not reading fast enough. */
            dropped: number;
            /**
             * @description What the stream is sampling at now. 1 is everything; 50 means one
             *     exchange in fifty is being sent.
             */
            ratio: number;
        };
        /** @enum {string} */
        ZoneKind: "forward" | "reverse";
        /** @description The start-of-authority parameters of a zone (RFC 1035 §3.3.13). */
        SOA: {
            /** @description The MNAME field, fully qualified. */
            primaryNs: string;
            /** @description The RNAME field, as a domain name. */
            mailbox: string;
            /**
             * Format: int64
             * @description Advanced by exactly one per commit (docs/decisions/ D2).
             */
            readonly serial: number;
            /** Format: int64 */
            refresh: number;
            /** Format: int64 */
            retry: number;
            /** Format: int64 */
            expire: number;
            /**
             * Format: int64
             * @description The negative-caching TTL of RFC 2308 §4, not a floor on record TTLs.
             */
            minimum: number;
            /**
             * Format: int64
             * @description The time to live of the SOA record itself.
             */
            ttl: number;
        };
        Zone: {
            id: string;
            /** @description The apex, fully qualified. */
            name: string;
            kind: components["schemas"]["ZoneKind"];
            /** @description The network a reverse zone answers for, in CIDR form. */
            prefix?: string;
            soa: components["schemas"]["SOA"];
            /**
             * Format: int64
             * @description Applied to a record added without one.
             */
            defaultTtl: number;
            /** @description Whether address records in this zone generate PTRs. Absent inherits the global setting. */
            autoReverse?: boolean;
            /** @description A disabled zone is invisible on the wire, not merely marked. */
            disabled: boolean;
            comment?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ZoneDetail: components["schemas"]["Zone"] & {
            /**
             * @description Name servers this zone points at and has no address for. A
             *     resolver following the delegation is told, authoritatively,
             *     that the name does not exist (RFC 1912 §2.8). Correct DNS and
             *     almost never intended, which is why it travels with the zone
             *     rather than only in a check.
             */
            lameNameServers: components["schemas"]["LameNameServer"][];
        };
        LameNameServer: {
            /**
             * @description What is wrong and what to do about it, in the same words the zone
             *     check uses. It travels with the answer so that no client writes its
             *     own version of the sentence.
             */
            detail: string;
            /**
             * @description The name the NS record sits on: the apex for this zone's own name
             *     servers, a child name for a delegation.
             */
            owner: string;
            /** @description The name server this zone has no address for. */
            target: string;
        };
        CreateZone: {
            /**
             * @description The apex. A trailing dot is optional; the name is absolute either
             *     way.
             *
             *     A network in CIDR notation is accepted here instead, and becomes
             *     the reverse zone that answers for it: `192.168.0.0/16` is
             *     `168.192.in-addr.arpa.`, `192.0.2.0/25` is the classless
             *     `0/25.2.0.192.in-addr.arpa.` of RFC 2317, and `2001:db8::/32` is
             *     eight nibbles written backwards. Working that out by hand is the
             *     first thing that sends somebody to a manual.
             *
             *     A prefix and a name cannot be confused for one another, so nothing
             *     is guessed. A bare address is refused with the network it probably
             *     meant.
             */
            name: string;
            soa?: components["schemas"]["SOAInput"];
            /** Format: int64 */
            defaultTtl?: number;
            comment?: string;
        };
        /**
         * @description The zone settings that may be changed. A field that is absent is left
         *     as it is, which is what makes this a partial edit rather than a
         *     replacement that a client has to read the whole zone to send.
         */
        UpdateZone: {
            soa?: components["schemas"]["SOAInput"];
            /** Format: int64 */
            defaultTtl?: number;
            /**
             * @description Whether address records in this zone generate PTRs. Null puts the
             *     zone back on the server-wide setting, which is a third state and
             *     not the same as false.
             */
            autoReverse?: boolean | null;
            /** @description A disabled zone stops answering entirely. */
            disabled?: boolean;
            comment?: string;
        };
        /**
         * @description The start-of-authority fields a client may set, on a zone it is
         *     creating and on one it is changing. Every field is optional in both
         *     cases: creating a zone fills what is not given from this server's
         *     defaults, and changing one leaves it as it was. A client that only
         *     cares about the name server should not have to send five timers it has
         *     no opinion about.
         *
         *     The serial is not among them: one commit advances it by exactly one,
         *     and that is what lets the journal be replayed (docs/decisions/ D2).
         */
        SOAInput: {
            primaryNs?: string;
            mailbox?: string;
            /** Format: int64 */
            refresh?: number;
            /** Format: int64 */
            retry?: number;
            /** Format: int64 */
            expire?: number;
            /** Format: int64 */
            minimum?: number;
            /** Format: int64 */
            ttl?: number;
        };
        ZonePage: {
            items: components["schemas"]["Zone"][];
            /** @description Absent once the listing is exhausted. */
            nextCursor?: string;
        };
        Record: {
            id: string;
            zoneId: string;
            /** @description The owner name, fully qualified. */
            name: string;
            type: string;
            class: string;
            /** Format: int64 */
            ttl: number;
            /** @description The record data in presentation format, canonicalised. */
            data: string;
            /** @description The record this one was generated from, for a generated record. */
            managedBy?: string;
            /** @description Why this record was generated. */
            managedKind?: string;
            comment?: string;
            disabled: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateRecord: {
            /**
             * @description The owner name, absolute. A trailing dot is optional and changes
             *     nothing: `www.example.com` and `www.example.com.` are the same
             *     name. A name is never completed with the zone apex; that is what
             *     turns `www.example.com` into `www.example.com.example.com.` in a
             *     zonefile, and an interface that offers a relative field completes
             *     it before it gets here.
             */
            name: string;
            type: string;
            /** @description Defaults to IN, which is the only class this server answers. */
            class?: string;
            /**
             * Format: int64
             * @description Defaults to the zone's own default TTL.
             */
            ttl?: number;
            data: string;
            comment?: string;
        };
        /**
         * @description The parts of a record that may be changed. A field that is absent is
         *     left as it is. The class is not among them, because IN is the only
         *     class this server answers.
         */
        UpdateRecord: {
            name?: string;
            type?: string;
            /** Format: int64 */
            ttl?: number;
            data?: string;
            comment?: string;
            /** @description A disabled record is kept but not answered with. */
            disabled?: boolean;
        };
        /** @description The record as it now stands, together with what writing it caused. */
        RecordWritten: {
            record: components["schemas"]["Record"];
            /** @description Records written automatically, such as the PTR for an address. */
            generated?: components["schemas"]["Record"][];
            conflicts?: components["schemas"]["Conflict"][];
            missingZones?: components["schemas"]["MissingZone"][];
        };
        RecordPage: {
            items: components["schemas"]["Record"][];
            nextCursor?: string;
        };
        /** @description The zone a file produced, and what reading it ran into. */
        ZoneImported: {
            zone: components["schemas"]["Zone"];
            /** @description How many records were written. */
            records: number;
            /**
             * @description Records the file carried that the zone could never answer with, so
             *     they were left out. Data rather than an error: whether the source
             *     zone meant them is a question for a person.
             */
            skipped?: components["schemas"]["SkippedRecord"][];
            conflicts?: components["schemas"]["Conflict"][];
            missingZones?: components["schemas"]["MissingZone"][];
        };
        SkippedRecord: {
            /** @description The record as the file had it, in presentation format. */
            record: string;
            /** @description Why the zone could never answer with it. */
            reason: string;
        };
        /** @description What checking a zone found. */
        ZoneCheck: {
            /** @description How many records were read. */
            records: number;
            /**
             * @description What is wrong, in the order the names were read. An empty list
             *     means the zone satisfies every rule the write path enforces.
             */
            findings: components["schemas"]["Finding"][];
            /**
             * @description True when the check stopped collecting findings. What is listed is
             *     still true; it is not all of it.
             */
            truncated: boolean;
        };
        /**
         * @description Whether the write path would refuse the finding. The only distinction a
         *     check draws, and not a scale.
         * @enum {string}
         */
        FindingSeverity: "error" | "warning";
        /**
         * @description Which rule produced a finding, so that a client can group or filter
         *     without reading the sentence.
         * @enum {string}
         */
        FindingScope: "owner" | "delegation" | "zone" | "nameserver" | "reverse";
        /** @description One thing wrong with a zone. Data rather than an error. */
        Finding: {
            severity: components["schemas"]["FindingSeverity"];
            scope: components["schemas"]["FindingScope"];
            /**
             * @description The owner name it is about, absolute. For a finding about the zone
             *     as a whole this is the apex.
             */
            name: string;
            /**
             * @description The record an action on this finding would address, where there is
             *     one. Absent for a finding about a name rather than about a record,
             *     which is most of them.
             */
            record?: string;
            /**
             * @description What is wrong, worded as the write path words its refusal, so that
             *     a zone repaired until the check is quiet is one it would accept.
             */
            detail: string;
        };
        /**
         * @description Every record sharing an owner name, class and type. The TTL belongs to
         *     the set rather than to each record: RFC 2181 §5.2 requires them to be
         *     equal, and a field that can be set inconsistently is one that will be.
         */
        RRset: {
            /** @description The owner name, absolute, as for a single record. */
            name: string;
            type: string;
            /** @description Defaults to IN, which is the only class this server answers. */
            class?: string;
            /**
             * Format: int64
             * @description Defaults to the zone's own default TTL.
             */
            ttl?: number;
            /** @description What the set should hold. Empty removes it. */
            records: components["schemas"]["RRsetMember"][];
        };
        RRsetMember: {
            data: string;
            comment?: string;
            /** @description A disabled record is kept but not answered with. */
            disabled?: boolean;
        };
        ReplaceRRsets: {
            rrsets: components["schemas"]["RRset"][];
            /** @description Why, for the history. */
            comment?: string;
        };
        /** @description The named RRsets as they now stand, and what writing them caused. */
        RRsetsWritten: {
            /** @description Every record now in the named RRsets, in the order the sets were given. */
            records: components["schemas"]["Record"][];
            /** @description Records written automatically, such as the PTR for an address. */
            generated?: components["schemas"]["Record"][];
            conflicts?: components["schemas"]["Conflict"][];
            missingZones?: components["schemas"]["MissingZone"][];
        };
        /**
         * @description What a commit did, for an interface that would rather say it than recite the events.
         * @enum {string}
         */
        CommitKind: "zone_create" | "zone_update" | "zone_delete" | "edit" | "import" | "rollback";
        /**
         * @description The interface a change arrived through.
         * @enum {string}
         */
        CommitSource: "api" | "cli" | "import" | "system";
        /** @description One atomic change to one zone. */
        Commit: {
            id: string;
            zoneId: string;
            /**
             * @description Carried on the commit rather than joined from the zone, because a
             *     commit outlives the zone: the last thing that happens to a zone is
             *     that someone deletes it.
             */
            zoneName: string;
            /**
             * Format: int64
             * @description The serial this commit was applied to.
             */
            serialFrom: number;
            /**
             * Format: int64
             * @description The serial it produced. Exactly one step on (docs/decisions/ D2).
             */
            serialTo: number;
            kind: components["schemas"]["CommitKind"];
            source: components["schemas"]["CommitSource"];
            /**
             * Format: int64
             * @description The serial a rollback restored the zone to. Absent on every other
             *     kind of commit, which is what the schema enforces.
             */
            revertsTo?: number;
            /** @description Who caused it, as far as the interface it arrived through could tell. */
            actor?: string;
            comment?: string;
            /** Format: date-time */
            createdAt: string;
            /**
             * @description The records this commit removed and added, in order. Absent in a
             *     listing, which is what keeps a page of history cheap.
             */
            events?: components["schemas"]["Event"][];
        };
        RollbackZone: {
            /**
             * Format: int64
             * @description The serial to restore the zone to. It has to be one the zone actually had.
             */
            serial: number;
            /** @description Why, for the history. */
            comment?: string;
        };
        /** @description What restoring the state produced. */
        RollbackResult: {
            /**
             * @description The commit that moved the zone to that state, with its events.
             *     Absent when the zone was already there and nothing was written.
             */
            commit?: components["schemas"]["Commit"];
            conflicts?: components["schemas"]["Conflict"][];
            missingZones?: components["schemas"]["MissingZone"][];
        };
        /** @description What filling a zone produced. */
        ReconcileResult: {
            /**
             * @description The commit that wrote the missing entries, with its events. Absent
             *     when the zone needed nothing.
             */
            commit?: components["schemas"]["Commit"];
            conflicts?: components["schemas"]["Conflict"][];
            missingZones?: components["schemas"]["MissingZone"][];
        };
        /**
         * @description One resource-record change. There is no "modify": a modification is a
         *     removal and an addition, which is how RFC 1995 §2 expresses it too.
         *     Both directions carry the full record data, so a removal can be undone
         *     as well as replayed.
         */
        Event: {
            /** @description Orders the events within the commit, counting from zero. */
            seq: number;
            /** @enum {string} */
            op: "add" | "del";
            name: string;
            class: string;
            type: string;
            /** Format: int64 */
            ttl: number;
            data: string;
        };
        CommitPage: {
            items: components["schemas"]["Commit"][];
            nextCursor?: string;
        };
        CreateSession: {
            /** @description The API token to open the session with. */
            token: string;
        };
        /** @description Who a request is authenticated as, and what it may do. */
        Session: {
            /** @description The name of the token this authenticates as. */
            name: string;
            scopes: components["schemas"]["Scope"][];
            /**
             * Format: date-time
             * @description When the session ends. Absent when the request authenticated with a bearer token.
             */
            expiresAt?: string;
        };
        /**
         * @description What a token may do. The scopes are ordered (admin allows everything
         *     write allows, and write everything read allows) so a token carries the
         *     strongest one it needs rather than a list.
         * @enum {string}
         */
        Scope: "read" | "write" | "admin";
        /** @description A credential, without the secret it authenticates with. */
        Token: {
            id: string;
            /** @description What this token is for, as a person would say it. */
            name: string;
            /**
             * @description The leading characters of the secret, kept in the clear so that two
             *     tokens can be told apart in a list and in the history.
             */
            prefix: string;
            scopes: components["schemas"]["Scope"][];
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Absent for a token that has never authenticated a request. Advisory, and may lag.
             */
            lastUsedAt?: string;
            /**
             * Format: date-time
             * @description Absent for a token that does not expire.
             */
            expiresAt?: string;
            /**
             * Format: date-time
             * @description Absent for a token that is still usable.
             */
            revokedAt?: string;
        };
        CreateToken: {
            name: string;
            scopes: components["schemas"]["Scope"][];
            /**
             * Format: date-time
             * @description When the token stops working. Absent means it does not.
             */
            expiresAt?: string;
        };
        TokenCreated: {
            token: components["schemas"]["Token"];
            /**
             * @description The credential itself, shown here and nowhere else. There is no way
             *     to read it again, because the server does not have it.
             */
            secret: string;
        };
        /** @description A key a secondary signs its transfer requests with, without its secret. */
        TSIGKey: {
            id: string;
            /**
             * @description The key name both ends agree on, in domain name syntax
             *     (RFC 8945 section 4.2). Compared case-insensitively.
             * @example secondary.example.com.
             */
            name: string;
            algorithm: components["schemas"]["TSIGAlgorithm"];
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Absent for a key that still signs.
             */
            revokedAt?: string;
        };
        /**
         * @description The keyed hash the key signs with. This server does not offer hmac-sha1
         *     or HMAC-MD5, which RFC 8945 section 6 calls NOT RECOMMENDED and MUST NOT
         *     use respectively; docs/decisions/ D28 argues the departure from its
         *     MUST-implement.
         * @enum {string}
         */
        TSIGAlgorithm: "hmac-sha256." | "hmac-sha384." | "hmac-sha512.";
        CreateTSIGKey: {
            /**
             * @description The key name, in domain name syntax.
             * @example secondary.example.com.
             */
            name: string;
            algorithm?: components["schemas"]["TSIGAlgorithm"];
            /**
             * @description The shared secret, base64. Absent means generate one, which is what
             *     an operator who is configuring both ends wants.
             */
            secret?: string;
        };
        TSIGKeySecret: {
            key: components["schemas"]["TSIGKey"];
            /** @description The shared secret, base64, as every implementation writes it. */
            secret: string;
        };
        /**
         * @description The software a configuration is written for. PowerDNS is absent on
         *     purpose rather than for want of a template: its zones live in a backend
         *     rather than in a file, so the equivalent is a list of commands, which is
         *     a different thing to generate.
         * @enum {string}
         */
        SecondaryFormat: "bind" | "knot";
        /** @description A configuration file for the other end of a zone transfer. */
        SecondaryConfig: {
            format: components["schemas"]["SecondaryFormat"];
            /**
             * @description The file itself, ready to be written where the other server reads
             *     it. It holds the transfer key's secret in clear.
             */
            content: string;
            /**
             * @description What about this arrangement will not work, in the order it is set up
             *     in. Empty where nothing is missing. Each entry states what holds;
             *     offering the fix beside it is a client's job, the way a zone check's
             *     findings work.
             */
            warnings: string[];
        };
        /**
         * @description Where one secondary stands on one zone, as of the last question it
         *     answered (docs/decisions/ D36).
         */
        SecondaryStanding: {
            /** @example example.com. */
            zone: string;
            /**
             * @description The secondary's address, as it appears on the notify list.
             * @example 192.0.2.53:53
             */
            target: string;
            /**
             * @description What the last finished question found. `unasked` is a pair the first
             *     question has not come back for yet. `ahead` is a secondary holding a
             *     newer serial than this server publishes, which means it took its
             *     copy from somewhere this server is not, and `unordered` the pair RFC
             *     1982 §3.2 declines to order. `silent` said nothing in time, and
             *     `noSerial` answered without one to read.
             * @enum {string}
             */
            state: "unasked" | "inStep" | "behind" | "ahead" | "unordered" | "silent" | "noSerial";
            /**
             * Format: int64
             * @description What the secondary last said it holds. Left out where it has never
             *     said. It is kept while a secondary is silent, so what is shown is
             *     the last thing anybody saw rather than nothing at all, and `state`
             *     is what says the reading is old.
             */
            serial?: number;
            /**
             * Format: int64
             * @description How many commits behind that serial is. D2 advances a zone by one
             *     per commit, so it counts changes rather than a distance. Left out
             *     unless the state is `behind`.
             */
            lag?: number;
            /**
             * Format: date-time
             * @description When the last question finished. Left out where none has.
             */
            askedAt?: string;
        };
        /**
         * @description An address already answers with another name (docs/decisions/ D3). It
         *     is data rather than an error: which name should be canonical is a
         *     decision for a person.
         */
        Conflict: {
            address: string;
            existingName: string;
            requestedName: string;
            existingRecordId?: string;
            /**
             * @description The policy that decided what happened here, so a client can say
             *     whether the existing name was kept, replaced or joined rather than
             *     leaving the reader to guess from the records.
             */
            policy: components["schemas"]["ReverseConflictPolicy"];
        };
        /**
         * @description A reverse entry has nowhere to go, because no zone covers the address.
         *     Creating one is an assertion of authority, so it is offered rather than
         *     done (docs/decisions/ D6).
         */
        MissingZone: {
            address: string;
            /** @description The reverse zone that would be needed. */
            zoneName: string;
        };
    };
    responses: {
        /** @description The request could not be carried out. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description The ULID of a zone. */
        ZoneID: string;
        /** @description The ULID of a record. */
        RecordID: string;
        /** @description Continue a listing where the last page ended. */
        Cursor: string;
        /** @description How many items to return at most. */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is serving. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The server is not ready to answer. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current values. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    streamQueries: {
        parameters: {
            query?: {
                /**
                 * @description Watch a name and everything below it. Matching is
                 *     case-insensitive (RFC 4343), so it finds a query however 0x20
                 *     encoding wrote it.
                 */
                name?: string;
                /** @description Watch only these question types. Repeat for more than one. */
                type?: string[];
                /**
                 * @description Watch only these response codes, by mnemonic, `NXDOMAIN`,
                 *     `REFUSED`. Repeat for more than one.
                 */
                rcode?: string[];
                /**
                 * @description Watch only this address or network, in CIDR notation. A bare
                 *     address is taken as a single host.
                 */
                client?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stream, until the client goes away. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listZones: {
        parameters: {
            query?: {
                /** @description Continue a listing where the last page ended. */
                cursor?: components["parameters"]["Cursor"];
                /** @description How many items to return at most. */
                limit?: components["parameters"]["Limit"];
                /** @description Restrict the listing to forward or to reverse zones. */
                kind?: components["schemas"]["ZoneKind"];
                /**
                 * @description Match one apex exactly. This is how a client turns a name a person
                 *     typed into the zone it belongs to; `search` cannot, because
                 *     `example.com` also matches `notexample.com`.
                 */
                name?: string;
                /** @description Match anywhere in the zone name, case-insensitively. */
                search?: string;
                /** @description Select only disabled or only enabled zones. */
                disabled?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of zones. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonePage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createZone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateZone"];
            };
        };
        responses: {
            /** @description The zone was created. */
            201: {
                headers: {
                    /** @description Where the new zone can be read. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The zone. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The zone is gone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    updateZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateZone"];
            };
        };
        responses: {
            /** @description The zone as it now stands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zone"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listRecords: {
        parameters: {
            query?: {
                /** @description Continue a listing where the last page ended. */
                cursor?: components["parameters"]["Cursor"];
                /** @description How many items to return at most. */
                limit?: components["parameters"]["Limit"];
                /** @description Match one owner name exactly. */
                name?: string;
                /** @description Match one record type. */
                type?: string;
                /**
                 * @description Match anywhere in the owner name or the record data,
                 *     case-insensitively. It is what backs the filter above a record
                 *     listing, the same way it does above the zone listing: `name` and
                 *     `type` answer "which record is this", and this answers "where does
                 *     192.0.2.10 appear".
                 */
                search?: string;
            };
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecord"];
            };
        };
        responses: {
            /** @description The record was added. */
            201: {
                headers: {
                    /** @description Where the new record can be read. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordWritten"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    importZone: {
        parameters: {
            query?: {
                /**
                 * @description Where relative names are resolved from, for a file that sets no
                 *     `$ORIGIN` of its own. Not needed otherwise.
                 */
                origin?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/dns": string;
            };
        };
        responses: {
            /** @description The zone was created from the file. */
            201: {
                headers: {
                    /** @description Where the new zone can be read. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneImported"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    exportZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The zone. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/dns": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    checkZone: {
        parameters: {
            query?: {
                /**
                 * @description Also report the reverse entries this zone's records imply and it
                 *     does not have. Off by default: working that out means planning the
                 *     write that would fix it, which holds the zone's write lock while it
                 *     runs, and a check is otherwise a read that blocks nothing.
                 */
                reverse?: boolean;
            };
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What the check found. No findings is a sound zone. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneCheck"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    reconcileZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What filling the zone produced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconcileResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    rollbackZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollbackZone"];
            };
        };
        responses: {
            /** @description The zone is back at that state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollbackResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    replaceRRsets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a zone. */
                zoneId: components["parameters"]["ZoneID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceRRsets"];
            };
        };
        responses: {
            /** @description The named RRsets as they now stand. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RRsetsWritten"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a record. */
                recordId: components["parameters"]["RecordID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Record"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a record. */
                recordId: components["parameters"]["RecordID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The record is gone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    updateRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a record. */
                recordId: components["parameters"]["RecordID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecord"];
            };
        };
        responses: {
            /** @description The record as it now stands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordWritten"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    detachRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a record. */
                recordId: components["parameters"]["RecordID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The record, now authored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordWritten"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    makeRecordCanonical: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a record. */
                recordId: components["parameters"]["RecordID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The record, and what claiming the entry wrote. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordWritten"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSession"];
            };
        };
        responses: {
            /** @description The session was opened. The cookies are in the headers. */
            201: {
                headers: {
                    /** @description The session cookie and the CSRF cookie. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session is over. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The settings in force. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettings"];
            };
        };
        responses: {
            /** @description The settings as they now stand. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateToken"];
            };
        };
        responses: {
            /** @description The token, with its secret shown for the only time. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenCreated"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a token. */
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The token can no longer be used. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    listTSIGKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TSIGKey"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createTSIGKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTSIGKey"];
            };
        };
        responses: {
            /** @description The key, with its secret. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TSIGKeySecret"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    revokeTSIGKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a key. */
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The key no longer signs. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    readTSIGKeySecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a key. */
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The key and its secret. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TSIGKeySecret"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSecondaryConfig: {
        parameters: {
            query: {
                /** @description The software the configuration is written for. */
                format: components["schemas"]["SecondaryFormat"];
                /**
                 * @description Where this server answers a transfer request, as an address with an
                 *     optional port. It is given rather than worked out: a server does not
                 *     know which of its addresses the world reaches it on, and a hidden
                 *     primary is named by no record to ask.
                 * @example 192.0.2.1
                 */
                primary: string;
                /**
                 * @description The address the configuration is for. It appears nowhere in the
                 *     output. Naming it is what lets the transfer and notify lists be
                 *     checked rather than only described.
                 * @example 198.51.100.53
                 */
                secondary?: string;
                /**
                 * @description Which zones to write out, by name. Repeat it for several; leaving it
                 *     out takes every zone this server holds, reverse zones among them.
                 */
                zone?: string[];
                /**
                 * @description The name of the TSIG key the secondary signs with. Where it is left
                 *     out and exactly one key is on the transfer list, that key is meant;
                 *     where several are, one has to be named.
                 */
                key?: string;
                /**
                 * @description Whether to write a key block at all. False writes a configuration
                 *     that signs nothing, for a secondary the transfer list grants by
                 *     address.
                 */
                signed?: boolean;
                /**
                 * @description Where the secondary keeps its copies of the zones. Left out, each
                 *     program is left the place it uses anyway.
                 */
                zoneDir?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The configuration, and what is wrong with the arrangement. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecondaryConfig"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSecondaryStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every zone asked about, on every secondary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecondaryStanding"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listCommits: {
        parameters: {
            query?: {
                /** @description Continue a listing where the last page ended. */
                cursor?: components["parameters"]["Cursor"];
                /** @description How many items to return at most. */
                limit?: components["parameters"]["Limit"];
                /** @description Restrict the history to one zone. */
                zoneId?: string;
                /** @description Restrict to commits of these kinds. */
                kind?: components["schemas"]["CommitKind"][];
                /**
                 * @description Restrict to changes with these causes. `system` is the server's own
                 *     doing, which in practice means the reverse entries it kept in step
                 *     with a change somebody made; leaving it out is how a reader sees
                 *     what people did without the entries that followed.
                 */
                source?: components["schemas"]["CommitSource"][];
                /** @description Match the recorded actor exactly. */
                actor?: string;
                /** @description Only commits at or after this time. */
                since?: string;
                /** @description Only commits before this time. */
                until?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getCommit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ULID of a commit. */
                commitId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The commit, with its events in order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Commit"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
