package api

import (
	"net/netip"
	"strings"
	"time"

	"github.com/wegweiserzone/wegweiser/internal/api/gen"
	"github.com/wegweiserzone/wegweiser/internal/apply"
	"github.com/wegweiserzone/wegweiser/internal/journal"
	"github.com/wegweiserzone/wegweiser/internal/zone"
)

// The conversions between the model and what the spec describes.
//
// They are written out rather than generated by tags on the model, because the
// two are allowed to differ and should: a serial is a struct inside so that "<"
// does not compile on it (RFC 1982), and a number outside because JSON has no
// better idea. Making the model carry JSON tags would let the wire format drag
// the model around by the nose.

// zoneToAPI renders a zone as the spec describes it.
func zoneToAPI(z *zone.Zone) gen.Zone {
	out := gen.Zone{
		Id:         string(z.ID),
		Name:       z.Name.String(),
		Kind:       gen.ZoneKind(z.Kind),
		Soa:        soaToAPI(z.SOA),
		DefaultTtl: int64(z.DefaultTTL),
		Disabled:   z.Disabled,
		CreatedAt:  z.CreatedAt,
		UpdatedAt:  z.UpdatedAt,
	}
	if z.Prefix.IsValid() {
		out.Prefix = ptr(z.Prefix.String())
	}
	if z.AutoReverse != nil {
		out.AutoReverse = ptr(*z.AutoReverse)
	}
	if z.Comment != "" {
		out.Comment = ptr(z.Comment)
	}
	return out
}

// soaToAPI renders the start-of-authority parameters.
func soaToAPI(s zone.SOA) gen.SOA {
	return gen.SOA{
		PrimaryNs: s.NS.String(),
		Mailbox:   s.Mbox.String(),
		Serial:    ptr(int64(s.Serial.Uint32())),
		Refresh:   int64(s.Refresh),
		Retry:     int64(s.Retry),
		Expire:    int64(s.Expire),
		Minimum:   int64(s.Minimum),
		Ttl:       int64(s.TTL),
	}
}

// recordToAPI renders a record.
func recordToAPI(r *zone.Record) gen.Record {
	out := gen.Record{
		Id:        string(r.ID),
		ZoneId:    string(r.ZoneID),
		Name:      r.Name.String(),
		Type:      r.Type.String(),
		Class:     r.Class.String(),
		Ttl:       int64(r.TTL),
		Data:      r.RData.String(),
		Disabled:  r.Disabled,
		CreatedAt: r.CreatedAt,
		UpdatedAt: r.UpdatedAt,
	}
	if r.ManagedBy != "" {
		out.ManagedBy = ptr(string(r.ManagedBy))
		out.ManagedKind = ptr(string(r.ManagedKind))
	}
	if r.Comment != "" {
		out.Comment = ptr(r.Comment)
	}
	return out
}

// recordsToAPI renders a slice of records.
func recordsToAPI(recs []*zone.Record) []gen.Record {
	out := make([]gen.Record, 0, len(recs))
	for _, r := range recs {
		out = append(out, recordToAPI(r))
	}
	return out
}

// commitToAPI renders a commit, with its events when it carries any.
func commitToAPI(c *journal.Commit) gen.Commit {
	out := gen.Commit{
		Id:         string(c.ID),
		ZoneId:     string(c.ZoneID),
		ZoneName:   c.ZoneName.String(),
		SerialFrom: int64(c.SerialFrom.Uint32()),
		SerialTo:   int64(c.SerialTo.Uint32()),
		Kind:       gen.CommitKind(c.Kind),
		Source:     gen.CommitSource(c.Source),
		CreatedAt:  c.CreatedAt,
	}
	if c.Actor != "" {
		out.Actor = ptr(c.Actor)
	}
	if c.Comment != "" {
		out.Comment = ptr(c.Comment)
	}
	if c.RevertsTo != nil {
		out.RevertsTo = ptr(int64(c.RevertsTo.Uint32()))
	}
	if len(c.Events) > 0 {
		events := make([]gen.Event, 0, len(c.Events))
		for i := range c.Events {
			events = append(events, eventToAPI(&c.Events[i]))
		}
		out.Events = &events
	}
	return out
}

// eventToAPI renders one record change.
func eventToAPI(e *journal.Event) gen.Event {
	return gen.Event{
		Seq:   e.Seq,
		Op:    gen.EventOp(e.Op),
		Name:  e.Name.String(),
		Class: e.Class.String(),
		Type:  e.Type.String(),
		Ttl:   int64(e.TTL),
		Data:  e.RData.String(),
	}
}

// conflictsToAPI renders what reverse automation declined to overwrite.
func conflictsToAPI(cs []apply.Conflict) *[]gen.Conflict {
	if len(cs) == 0 {
		return nil
	}
	out := make([]gen.Conflict, 0, len(cs))
	for i := range cs {
		out = append(out, gen.Conflict{
			Address:       cs[i].Address.String(),
			ExistingName:  cs[i].Existing.String(),
			RequestedName: cs[i].SourceName.String(),
			Policy:        gen.ReverseConflictPolicy(cs[i].Policy),
		})
	}
	return &out
}

// missingZonesToAPI renders the reverse zones that would have been needed.
func missingZonesToAPI(ms []apply.MissingZone) *[]gen.MissingZone {
	if len(ms) == 0 {
		return nil
	}
	out := make([]gen.MissingZone, 0, len(ms))
	for _, m := range ms {
		out = append(out, gen.MissingZone{
			Address:  m.Address.String(),
			ZoneName: m.Suggested.String(),
		})
	}
	return &out
}

// parseName reads a name a client sent, refusing it as a bad request rather
// than as a server failure.
func parseName(what, s string) (zone.Name, error) {
	n, err := zone.ParseName(s)
	if err != nil {
		return zone.Name{}, badRequest("%s %q is not a domain name: %v", what, s, err)
	}
	return n, nil
}

// zoneApex reads what a person means by "the zone to create".
//
// A network in CIDR form becomes the reverse zone answering for it, because
// working that out by hand is the first thing that sends somebody to a manual:
// 192.168.0.0/16 is 168.192.in-addr.arpa, 192.0.2.0/25 is the classless
// 0/25.2.0.192.in-addr.arpa of RFC 2317, and 2001:db8::/32 is eight nibbles
// written backwards. The server already knows how to derive all three, and
// there is no reason for that knowledge to stop at the API.
func zoneApex(s string) (zone.Name, error) {
	if p, err := netip.ParsePrefix(s); err == nil {
		name, nerr := zone.ReverseZoneName(p)
		if nerr != nil {
			return zone.Name{}, badRequest("%v", nerr)
		}
		return name, nil
	}

	// A bare address is the near miss worth catching. It parses as a name,
	// since all-numeric labels are legal, so without this it would quietly
	// create a forward zone called "192.168.0.0." for somebody who meant a
	// network.
	if addr, err := netip.ParseAddr(s); err == nil {
		suggest := netip.PrefixFrom(addr, 24)
		if addr.Is6() {
			suggest = netip.PrefixFrom(addr, 64)
		}
		return zone.Name{}, badRequest(
			"%q is an address, not a network: say %s for the reverse zone that answers for it, "+
				"or a domain name for a forward zone", s, suggest.Masked())
	}

	return parseName("the zone name", s)
}

// outsideZone refuses a name that does not belong to the zone it was sent to,
// and guesses at what was meant.
func outsideZone(z *zone.Zone, name zone.Name) error {
	if qualified, ok := underApex(z, name); ok {
		return badRequest("%q does not lie inside the zone %q; did you mean %q?",
			name, z.Name, qualified)
	}
	return badRequest("%q does not lie inside the zone %q", name, z.Name)
}

// underApex returns the name read as if it had been relative to the apex, when
// that produces a name the zone does hold.
func underApex(z *zone.Zone, name zone.Name) (zone.Name, bool) {
	if name.IsRoot() {
		return zone.Name{}, false
	}
	under, err := zone.ParseName(strings.TrimSuffix(name.String(), ".") + "." + z.Name.String())
	if err != nil || !z.Contains(under) {
		return zone.Name{}, false
	}
	return under, true
}

// ttlFrom reads a TTL a client sent, refusing one that is out of range rather
// than truncating it into range. A TTL of 2^40 is a mistake, and silently
// storing the low bits of it would answer with a number nobody asked for.
func ttlFrom(what string, v int64) (zone.TTL, error) {
	if v < 0 || v > int64(zone.MaxTTL) {
		return 0, badRequest("%s of %d is not a TTL; the range is 0 to %d (RFC 2181 §8)",
			what, v, zone.MaxTTL)
	}
	return zone.TTL(v), nil
}

// ptr is the pointer an optional field in the generated models wants.
func ptr[T any](v T) *T { return &v }

// deref reads an optional field, falling back to a default.
func deref[T any](p *T, fallback T) T {
	if p == nil {
		return fallback
	}
	return *p
}

// time0 is the zero time, as something deref can be handed: a filter bound
// that was not sent is not a bound.
var time0 time.Time

// zoneDetailToAPI renders a zone together with the one diagnosis it carries.
func zoneDetailToAPI(z *zone.Zone, lame []zone.NameServer) gen.ZoneDetail {
	base := zoneToAPI(z)
	out := gen.ZoneDetail{
		Id: base.Id, Name: base.Name, Kind: base.Kind, Soa: base.Soa,
		DefaultTtl: base.DefaultTtl, Disabled: base.Disabled,
		Prefix: base.Prefix, AutoReverse: base.AutoReverse, Comment: base.Comment,
		CreatedAt: base.CreatedAt, UpdatedAt: base.UpdatedAt,

		// Never nil: a client ranging over it should not have to test first,
		// and "no lame name servers" is an answer rather than an absence.
		LameNameServers: make([]gen.LameNameServer, 0, len(lame)),
	}
	for _, ns := range lame {
		out.LameNameServers = append(out.LameNameServers, gen.LameNameServer{
			Owner:  ns.Owner.String(),
			Target: ns.Target.String(),
			Detail: zone.LameDetail(ns.Target),
		})
	}
	return out
}
